version: 2
updates:
- package-ecosystem: npm
  directory: "/trestle-server"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular-eslint/eslint-plugin-template"
    versions:
    - 2.0.2
    - 2.1.0
    - 4.0.0
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.2
    - 11.2.1
    - 11.2.10
    - 11.2.2
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular-eslint/template-parser"
    versions:
    - 2.0.2
    - 2.1.0
    - 4.0.0
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1101.2
    - 0.1102.0
    - 0.1102.1
    - 0.1102.10
    - 0.1102.2
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.7
    - 3.6.8
    - 3.6.9
  - dependency-name: jasmine-core
    versions:
    - 3.7.0
  - dependency-name: "@angular-eslint/schematics"
    versions:
    - 2.0.1
    - 2.0.2
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.5
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.2
    - 4.16.1
    - 4.17.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.32
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.2
    - 4.16.1
  - dependency-name: protractor-cucumber-framework
    versions:
    - 7.0.0
    - 7.0.2
    - 8.0.0
  - dependency-name: typescript
    versions:
    - 4.1.5
  - dependency-name: eslint
    versions:
    - 7.20.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.15
  - dependency-name: "@types/mapbox-gl"
    versions:
    - 2.0.4
    - 2.0.5
  - dependency-name: eslint-plugin-rxjs
    versions:
    - 2.1.7
    - 3.0.0
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.4.0
  - dependency-name: "@auth0/angular-jwt"
    versions:
    - 5.0.2
  - dependency-name: "@angular-eslint/eslint-plugin"
    versions:
    - 2.0.1
  - dependency-name: "@angular-eslint/builder"
    versions:
    - 2.0.1
  - dependency-name: chai
    versions:
    - 4.3.3
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.fasterxml.woodstox:woodstox-core
    versions:
    - 6.2.5
  - dependency-name: org.wololo:jts2geojson
    versions:
    - 0.16.0
  - dependency-name: org.eclipse.rdf4j:rdf4j-bom
    versions:
    - 3.6.2
  - dependency-name: com.zaxxer:HikariCP
    versions:
    - 4.0.2
  - dependency-name: com.ontotext.graphdb:graphdb-free-runtime
    versions:
    - 9.5.1
    - 9.6.0
  - dependency-name: com.nickrobison:fasttuple-core
    versions:
    - 0.3.3
  - dependency-name: dev.clojurephant.clojure
    versions:
    - 0.6.0-beta.1
  - dependency-name: it.unimi.dsi:fastutil
    versions:
    - 8.5.1
  - dependency-name: io.dropwizard:dropwizard-bom
    versions:
    - 2.0.18
