pool:
  vmImage: 'ubuntu-16.04'

resources:
  containers:
    - container: graphdb
      registry: dockerHub
      image: nickrobison/graphdb:8.2.0-free
      ports:
        - 7200

services:
  graphdb: graphdb

steps:
  - task: Docker@2
    displayName: Login for Private Docker Images
    inputs:
      command: login
      containerRegistry: dockerHub
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      goals: 'test'