version: '3'

services:
  graphdb:
    image: docker.nickrobison.com:5000/evaluation-data
    ports:
      - "7200:7200"

  db:
    image: postgres:10.1
    ports:
      - "5432:5432"

  trestle:
    depends_on:
      - graphdb
      - db
    image: docker.nickrobison.com:5000/trestle-server:0.8.0-SNAPSHOT
    environment:
      CS: http://graphdb:7200

  nginx:
    depends_on:
      - trestle
    image: docker.nickrobison.com:5000/nginx-proxy
    ports:
      - "443:4443"
