version: '3'

services:
  graphdb:
    image: ontotext/graphdb:8.4.1-free
    ports:
      - "7200:7200"

  db:
    image: postgres:10.1
    ports:
      - "5432:5432"

  server:
    depends_on:
      - graphdb
      - db
    image: nickrobison/trestle-server:0.8.0-SNAPSHOT
    environment:
      CS: http://graphdb:7200
    ports:
      - "88:8080"
