reasoner:
#  connectionString: "jdbc:oracle:thin:@//oracle7.hobbithole.local:1521/spatial"
#  username: "spatialUser"
#  password: "spatial1"
  connectionString: "http://localhost:7200"
  username: ""
  password: ""
  ontology: "hadoop_gaul_expanded"
  prefix: "http://nickrobison.com/test/hadoop.owl#"
#  ontology: "tigercounties3"
#  prefix: "http://nickrobison.com/demonstration/tigercounty#"
  location: "file:////Users/nrobison/Developer/git/dissertation/trestle/ontology/trestle.owl"

logging:
  level: INFO
  loggers:
    "com.nickrobison.metrician": DEBUG
    "com.nickrobison.trestle": DEBUG

database:
  driverClass: org.h2.Driver
  user: sa
  url: jdbc:h2:./trestle.db
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect

jwt:
  authHeader: "Authorization"
  authSalt: "test-salt"