reasoner:
#  connectionString: "jdbc:oracle:thin:@//oracle7.hobbithole.local:1521/spatial"
#  username: "spatialUser"
#  password: "spatial1"
  connectionString: "http://localhost:7200"
  username: ""
  password: ""
#  connectionString: "http://141.142.170.88:7200/"
#  username: ""
#  password: ""
#  ontology: "hadoop_gaul_expanded_equality"
#  prefix: "http://nickrobison.com/test/gaul/"
#  prefix: "http://nickrobison.com/test/hadoop.owl#"
#  ontology: "tigercounties3"
#  prefix: "http://nickrobison.com/demonstration/tigercounty#"
  ontology: "gaul_hadoop_world_bank"
  prefix: "http://nickrobison.com/gaul/"
  location: "file:////Users/nickrobison/Developer/git/dissertation/trestle-ontology/trestle.owl"

logging:
  level: INFO
  loggers:
    "com.nickrobison.metrician": DEBUG
    "com.nickrobison.trestle": DEBUG
  appenders:
    - type: console
      logFormat: "[%-5p | %t | %X{test}] %d %c:%L %X{transaction} - %m%n"
      includeCallerData: true

database:
  driverClass: org.h2.Driver
  user: sa
  url: jdbc:h2:./trestle.db
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect

jwt:
  authHeader: "Authorization"
  authSalt: "test-salt"
  expirationTime: 7200

swagger:
  resourcePackage: com.nickrobison.trestle.server.resources
