reasoner:
  connectionString: "http://graphdb:7200"
  username: ""
  password: ""
  ontology: "e2e_tests"
  prefix: "http://nickrobison.com/gaul/"
  location: "file:///opt/trestle/trestle.owl"

logging:
  level: INFO
  appenders:
    - type: console
      logFormat: "[%-5p | %t | %X{test}] %d %c:%L %X{transaction} - %m%n"
      includeCallerData: true

database:
# Embedded H2
  driverClass: org.h2.Driver
  user: sa${CMDLINE}
  url: jdbc:h2:/opt/trestle/trestle.db
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect

jwt:
  authHeader: "Authorization"
  authSalt: "test-salt"
  expirationTime: 7200

swagger:
  resourcePackage: com.nickrobison.trestle.server.resources

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8087
